module InvoiceHelper
	def states
    [
      ['Delhi'],
      ['Andra Pradesh'],
      ['Arunachal Pradesh'],
      ['Assam'],
      ['Bihar'],
      ['Chhattisgarh'],
      ['Goa'],
      ['Gujarat'],
      ['Haryana'],
      ['Himachal Pradesh'],
      ['Jammu and Kashmir'],
      ['Jharkhand'],
      ['Karnataka'],
      ['Kerala'],
      ['Madhya Pradesh'],
      ['Maharashtra'],
      ['Manipur'],
      ['Meghalaya'],
      ['Mizoram'],
      ['Nagaland'],
      ['Orissa'],
      ['Punjab]'],
      ['Rajasthan'],
      ['Sikkim'],
      ['Tamil Nadu'],
      ['Telangana'],
      ['Tripura'],
      ['Uttarakhand'],
      ['Uttar Pradesh'],
      ['West Bengal'],
      ['Andaman and Nicobar Islands'],
      ['Chandigarh'],
      ['Dadar and Nagar Haveli'],
      ['Daman and Diu'],
      ['Lakshadweep'],
      ['Puducherry'],
    ]
 end
end
